[package]
name = "godot_enet"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
log = "0.4.28"
md5 = "0.8.0"
rand = "0.9.2"
rusty_enet = "0.4"
tokio = { version = "1.47.1", features = ["full"] }

[dev-dependencies]
colog = "1.3.0"
