[package]
name = "godot_enet"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
rusty_enet = "0.4"
tokio = { version = "1.47.1", features = ["full"] }

[dev-dependencies]
colog = "1.3.0"
